### ISSUE TITLE
Radio Button System.TypeInitializationException

### ISSUE THREAD

**Issue by gcouchbit** [enisn/Xamarin.Forms.InputKit#124]
I have recently started having an issue with radio buttons.   I am using vs2019.    I have implemented the nugget with the exact code from the documentation and i get the following exception.  I have been using the nugget for 6-8 months and it has worked wonderfully.    Since the update to vs2019 and the update to 3.0.8.   This issue has occurred.   It occurs on iOS and Android.   The other controls seem to work fine,  it just seems to happen when i implement Radio Buttons. 

Thanks! 

```xml
   <input:RadioButtonGroupView>
                <input:RadioButton Text="Option 1" />
                <input:RadioButton Text="Option 2" />
                <input:RadioButton Text="Option 3" />
                <input:RadioButton Text="Option 4" />
            </input:RadioButtonGroupView>
```

Here is the InnerException i am receiving. 

{System.ArgumentException: Default value did not match return type
Parameter name: defaultValue
  at Xamarin.Forms.BindableProperty..ctor (System.String propertyName, System.Type returnType, System.Type declaringType, System.Object defaultValue, Xamarin.Forms.BindingMode defaultBindingMode, Xamarin.Forms.BindableProperty+ValidateValueDelegate validateValue, Xamarin.Forms.BindableProperty+BindingPropertyChangedDelegate propertyChanged, Xamarin.Forms.BindableProperty+BindingPropertyChangingDelegate propertyChanging, Xamarin.Forms.BindableProperty+CoerceValueDelegate coerceValue, Xamarin.Forms.BindableProperty+BindablePropertyBindingChanging bindingChanging, System.Boolean isReadOnly, Xamarin.Forms.BindableProperty+CreateDefaultValueDelegate defaultValueCreator) [0x0008d] in D:\a\1\s\Xamarin.Forms.Core\BindableProperty.cs:77 
  at Xamarin.Forms.BindableProperty.Create (System.String propertyName, System.Type returnType, System.Type declaringType, System.Object defaultValue, Xamarin.Forms.BindingMode defaultBindingMode, Xamarin.Forms.BindableProperty+ValidateValueDelegate validateValue, Xamarin.Forms.BindableProperty+BindingPropertyChangedDelegate propertyChanged, Xamarin.Forms.BindableProperty+BindingPropertyChangingDelegate propertyChanging, Xamarin.Forms.BindableProperty+CoerceValueDelegate coerceValue, Xamarin.Forms.BindableProperty+CreateDefaultValueDelegate defaultValueCreator) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableProperty.cs:137 
  at Plugin.InputKit.Shared.Controls.RadioButton..cctor () [0x003cf] in <xxxxxxxxxxxxxxxxxxx>:0 }

Here is the StackTrace

"  at OrangeSheets.MainPage..ctor () [0x00008] in /Users/XXXX/Projects/XXXXX/XXXXXXXX/MainPage.xaml.cs:18 \n  at XXXXX.App..ctor () [0x0000f] in /Users/XXXX/Projects/XXXX/XXXX/App.xaml.cs:13 \n  at XXXX.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00037] in /Users/XXXX/Projects/XXX/XXXXX.Android/MainActivity.cs:28 \n  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <2960acf2eeb24d88b5230e1e8afbdc2e>:0 \n  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.8(intptr,intptr,intptr)"

**Comment by jlhernandez1388** [comment]
I'm having the same exception since the last Xamarin.Forms update. Any luck yet?

**Comment by jlhernandez1388** [comment]
Apparently the issue has to do with iOS 12.2 it works ok in iOS 12.1.

**Comment by mabdollahiasl** [comment]
I have the same problem, what should I do :(

**Comment by enisn** [comment]
That should be fixed at [v3.0.10](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v3.0.10)

Can you check again ?

**Comment by mabdollahiasl** [comment]
> That should be fixed at v3.0.10
> Can you check again ?

No, Unfortunately the problem is not solved!

**Comment by gcouchbit** [comment]
Confirmed.   I still receive the same exception on both iOS and Android using 3.0.10.

**Comment by jlhernandez1388** [comment]
Still same problem!

**Comment by cortensinger** [comment]
Same problem on my end

**Comment by abastias** [comment]
I am having the same issue (just RadioButton) with iOS and Android. There something in the installation/init that makes this issue. I can not find. However I downloaded the demo app, and works fine...

This is the error:

Unhandled Exception:

System.TypeInitializationException: The type initializer for 'Plugin.InputKit.Shared.Controls.RadioButton' threw an exception.

**Comment by piratecharly** [comment]
Same problem!  Fix it, pleae.

**Comment by stavroaudi** [comment]
Same here

**Comment by zalza13** [comment]
Same for me!! :( 

What version of Xamarin.Forms do you have?

System.TypeInitializationException: The type initializer for 'Plugin.InputKit.Shared.Controls.RadioButton' threw an exception

**Comment by zalza13** [comment]
@enisn @stavroaudi @piratecharly @abastias @cortensinger @gcouchbit @mabdollahiasl 

---> I found the error! .. **the solution was not yet published in the nuget package**. Please, look at the image below. The package dll 3.0.10 **does not contain the commit fix** c6ab5209f91edda375b742edca3dc72d6c23c6cd

![radiobutton_error](https://user-images.githubusercontent.com/9556967/56838318-2c7d0880-6843-11e9-9c5c-d44b41079df5.png)

**Comment by enisn** [comment]
@zalza13 
oh yes, sorry about it. It haven't published yet.

**Comment by zalza13** [comment]
> 
> 
> @zalza13
> oh yes, sorry about it. It haven't been published yet.

Thanksss!! there is not error any more!!!
