### ISSUE TITLE
SelectView background color applied only after selection

### ISSUE THREAD

**Issue by antosubash** [enisn/Xamarin.Forms.InputKit#55]
How do I display a background color for all controls inside the selection view?

![screenshot_1541714349](https://user-images.githubusercontent.com/1304254/48230236-a3fccf80-e3aa-11e8-8c60-dc29241d972b.png)

**Comment by enisn** [comment]
@antosubash 
There is a Global Options inside SelectionView class. 

Try use this code is your **App.cs** before you set **MainPage**:

```csharp
             SelectionView.GlobalSetting.BackgroundColor = Color.Blue;
```

All controls have GlobalSetting and it sets defaults of controls.

I think it'll solve problem. If you're using other SelectionTypes like CheckBox or RadioButton, you should set `CheckBox.GlobalSettings` 

If it doesn't affect,, I can add new properties to **SelectionView**

**Comment by antosubash** [comment]
@enisn Thanks for the info.

I have already tried it. it didn't work.

this only happens on Android. It works fine on IOS.

**Comment by enisn** [comment]
OK. I'm working on it.
Thanks for your feedback 👍

**Comment by antosubash** [comment]
@enisn Great. 

This is how I fixed the issue for now. 
```
        protected override void OnAppearing()
        {
            base.OnAppearing();

            // TODO : Remove after the fix of https://github.com/enisn/Xamarin.Forms.InputKit/issues/55
            if (Device.RuntimePlatform == Device.Android)
            {
                SelectView.Children.ForEach((obj) => obj.BackgroundColor = Color.LightGray);
            }
        }
```

**Comment by enisn** [comment]
> @enisn Great.
> 
> This is how I fixed the issue for now.
> 
> ```
>         protected override void OnAppearing()
>         {
>             base.OnAppearing();
> 
>             // TODO : Remove after the fix of https://github.com/enisn/Xamarin.Forms.InputKit/issues/55
>             if (Device.RuntimePlatform == Device.Android)
>             {
>                 SelectView.Children.ForEach((obj) => obj.BackgroundColor = Color.LightGray);
>             }
>         }
> ```

Thanks for your contribution 👍 ❤️   I'm fixing immediately! 
@antosubash

**Comment by enisn** [comment]
@antosubash 
It was just solved with [v.2.3.5 Release](https://github.com/enisn/Xamarin.Forms.InputKit/releases/tag/v.2.3.5) 


You can use **BackgroundColor** property of SelectionView to set default unselected color of buttons.
Also SelectionView.GlobalSetting.BackgrounColor works to change all SelectionViews defaults too.

xaml:
```xml
<input:SelectionView BackgroundColor="Yellow" />
```
cs:
```csharp
     selectionView.BackgroundColor = Color.Yellow;
      // or Globally:
     SelectionView.GlobalSetting.BackgroundColor = Color.Yellow;
```

Nuget is [here](https://www.nuget.org/packages/Xamarin.Forms.InputKit/2.3.5).

**Comment by antosubash** [comment]
@enisn Thanks for the quick release. I think it is not fixed properly yet.

This is not working 
`SelectionView.GlobalSetting.BackgroundColor = Color.Yellow;`

When I set this.
`<input:SelectionView BackgroundColor="Yellow" />`

This is the output
![image](https://user-images.githubusercontent.com/1304254/48317692-2a592180-e5f6-11e8-8bcc-ecaf3501725d.png)

The corner is not round initial and becomes round after click.

**Comment by enisn** [comment]
> @enisn Thanks for the quick release. I think it is not fixed properly yet.
> 
> This is not working
> `SelectionView.GlobalSetting.BackgroundColor = Color.Yellow;`
> 
> When I set this.
> `<input:SelectionView BackgroundColor="LightGray" />`
> 
> This is the output
> ![image](https://user-images.githubusercontent.com/1304254/48317692-2a592180-e5f6-11e8-8bcc-ecaf3501725d.png)
> 
> The corner is not round initial and becomes round after click.

Are these 4 options in same SelectionView and Corner Radius is different ?

**Comment by antosubash** [comment]
@enisn they are from the same selection view. the corner radius changes after selection.

**Comment by enisn** [comment]
> @enisn they are from the same selection view. the corner radius changes after selection.

Can you share part of your code ? 
I can't handled same problem on my test project

**Comment by antosubash** [comment]
@enisn 

`<controls:SelectionView x:Name="Severity" SelectedItem="{Binding SelectedSeverity}" ItemsSource="{Binding Severity}" ColumnNumber="2" ColumnSpacing="10" RowSpacing="10" SelectionType="Button" />`

**Comment by enisn** [comment]
> @enisn I'm really sorry. it works. I just created a new project and tested it.
> 
> I have deleted the obj and bin folder. And tried again and it works perfectly. Thanks again.

Have a good work! 👍 😃
